# Generated by Django 4.1 on 2022-12-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=200)),
                ('location', models.CharField(max_length=800)),
                ('service', models.CharField(max_length=200)),
            ],
        ),
    ]
