# Generated by Django 4.1 on 2022-12-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_serviceform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceform',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
