# Generated by Django 4.1 on 2022-12-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_serviceform_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceform',
            name='service',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
