# Generated by Django 4.1 on 2022-12-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_serviceform_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceform',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
