# Generated by Django 4.1 on 2022-12-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_serviceform_date_alter_serviceform_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceform',
            old_name='contact',
            new_name='ccontact',
        ),
        migrations.RenameField(
            model_name='serviceform',
            old_name='date',
            new_name='cdate',
        ),
        migrations.RenameField(
            model_name='serviceform',
            old_name='email',
            new_name='cemail',
        ),
        migrations.RenameField(
            model_name='serviceform',
            old_name='location',
            new_name='clocation',
        ),
        migrations.RenameField(
            model_name='serviceform',
            old_name='name',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='serviceform',
            old_name='service',
            new_name='cservice',
        ),
    ]
